---
- hosts: all
  sudo: yes
  pre_tasks:
    - name: Get ansible_user home directory
      shell: 'getent passwd "{{ansible_ssh_user}}" | cut -d: -f6'
      register: ansible_home_result
  
    - name: Set the fact for the other scripts to use
      set_fact: ansible_home='{{ansible_home_result.stdout}}'
  tasks:
    - name: set timezone to Asia/Tokyo
      file: src=/usr/share/zoneinfo/Asia/Tokyo  dest=/etc/localtime state=link force=yes
    - name: install zsh
      yum: name=zsh state=installed
    - name: install vim
      yum: name=vim state=installed
    - name: install git
      yum: name=git state=installed
    - name: git clone rbenv
      git: repo=git@github.com:rbenv/rbenv.git dest={{ ansible_home }} version={{ branch }} accept_hostkey=yes
    - name: git clone pyenv
      git: repo=git@github.com:yyuu/pyenv.git dest={{ ansible_home }} version={{ branch }} accept_hostkey=yes
