# /roles/common/tasks/Darwin.yml

- name: check if brew command exist
  stat:
    path: /opt/homebrew/bin/brew
  register: file

# https://brew.sh/index_ja
- name: install homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not file.stat.exists

- name: install common applications
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  with_items:
    - git
    - gh
    - htop
    - tmux
    - vim
    - zsh
    - anyenv

# Rosetta
- name: check if Rosetta command exist
  stat:
    path: /System/Library/CoreServices/Rosetta 2 Updater.app
  register: file

- name: install rosetta
  shell: softwareupdate --install-rosetta --agree-to-license
  when: not file.stat.exists
  become: true

# Google Chrome
- name: check if google chrome exist
  stat:
    path: /Applications/Google Chrome.app
  register: file

- name: install google chrome
  shell: brew install google-chrome --cask
  when: not file.stat.exists

# Google Japanese IME
- name: check if google japanese IME exist
  stat:
    path: /Applications/GoogleJapaneseInput.localized
  register: file

- name: install google chrome
  shell: brew install google-japanese-ime --cask
  when: not file.stat.exists

# Backup and sync
- name: check if google drive exist
  stat:
    path: /Applications/Google Drive.app
  register: file

- name: install google drive
  shell: brew install google-drive --cask
  when: not file.stat.exists

# Alfred
- name: check if alfred exist
  stat:
    path: /Applications/Alfred 4.app
  register: file

- name: install alfred
  shell: brew install alfred --cask
  when: not file.stat.exists

# Visual Studio Code
- name: check if visual studio code exist
  stat:
    path: /Applications/Visual Studio Code.app
  register: file

- name: install visual studio code
  shell: brew install visual-studio-code --cask
  when: not file.stat.exists

# Adobe Acrobat Reader
- name: check if acrobat reader exist
  stat:
    path: /Applications/Adobe Acrobat Reader DC.app
  register: file

- name: install acrobat reader
  shell: brew install adobe-acrobat-reader --cask
  when: not file.stat.exists

# Spectacle
- name: check if spectacle exist
  stat:
    path: /Applications/Spectacle.app
  register: file

- name: install spectacle
  shell: brew install spectacle --cask
  when: not file.stat.exists

# iTerm2
- name: check if iterm2 exist
  stat:
    path: /Applications/iTerm.app
  register: file

- name: install spectacle
  shell: brew install iterm2 --cask
  when: not file.stat.exists

# Slack
- name: check if slack exist
  stat:
    path: /Applications/Slack.app
  register: file

- name: install slack
  shell: brew install slack --cask
  when: not file.stat.exists

# mkdir ~/.zsh
- name: ~/.zsh directory
  file:
      path: ~/.zsh
      state: directory
