---
- name: tatsukawa's environment
  hosts: localhost
  connection: local

  roles:
    - { role: common }
    - { role: dein }
    - { role: zplug }
    - { role: dotfiles }
    - { 
        role: ubuntu_env,
        when: "{{ ansible_os_family }} == 'RedHat'"
      }
  
